# Generated by Django 3.1.9 on 2021-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210518_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='button_text_01',
            new_name='button_text_01_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='button_text_02',
            new_name='button_text_02_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='button_text_03',
            new_name='button_text_03_2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_01_2',
            field=models.CharField(default='Read More', help_text='Button text 01', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_02_2',
            field=models.CharField(default='Read More', help_text='Button text 02', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_03_1',
            field=models.CharField(default='Read More', help_text='Button text 03', max_length=50),
        ),
    ]
