# Generated by Django 3.1.9 on 2021-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210518_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sub_text_down',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_down_01',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_down_02',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_down_03',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_text_up',
            field=models.CharField(blank=True, help_text='Subheading text above the heading title', max_length=255),
        ),
    ]
