# Generated by Django 3.1.9 on 2021-05-24 17:12

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    replaces = [('home', '0003_auto_20210518_1402'), ('home', '0004_auto_20210518_1417'), ('home', '0005_auto_20210518_1434'), ('home', '0006_auto_20210518_1447'), ('home', '0007_auto_20210518_1530'), ('home', '0008_homepage_body'), ('home', '0009_auto_20210519_1015'), ('home', '0010_auto_20210519_1053'), ('home', '0011_auto_20210519_1055'), ('home', '0012_auto_20210519_1557'), ('home', '0013_auto_20210519_2030'), ('home', '0014_auto_20210520_1757'), ('home', '0015_auto_20210520_2126'), ('home', '0016_auto_20210520_2152'), ('home', '0017_auto_20210521_1226'), ('home', '0018_auto_20210521_1343'), ('home', '0019_auto_20210521_1809'), ('home', '0020_auto_20210522_1844'), ('home', '0021_auto_20210522_1928'), ('home', '0022_auto_20210522_2010'), ('home', '0023_auto_20210522_2024'), ('home', '0024_auto_20210523_1634'), ('home', '0025_auto_20210523_1920')]

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_personal_image',
            field=models.ForeignKey(help_text='Banner personal image 968x945', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_background_image',
            field=models.ForeignKey(help_text='Banner background image 1902x952', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lead_text',
            field=models.CharField(blank=True, help_text='Heading text under the banner title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_up',
            field=models.CharField(blank=True, help_text='Subheading text above the heading title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_01',
            field=models.ForeignKey(blank=True, help_text='Select an optional page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_02',
            field=models.URLField(blank=True, help_text='Write the url to link to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_03',
            field=models.URLField(blank=True, help_text='Write the url to link to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_down_01',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title 1', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_down_02',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title 2', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text_down_03',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title 3', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_01_1',
            field=models.CharField(default='Download CV', help_text='Button text 01 1', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_01_2',
            field=models.CharField(default='Download', help_text='Button text 01 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_02_1',
            field=models.CharField(default='Send Message', help_text='Button text 02 1', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_02_2',
            field=models.CharField(default='SEND', help_text='Button text 02 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_03_1',
            field=models.CharField(default='Hire Me', help_text='Button text 03 1', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_03_2',
            field=models.CharField(default='HIRE', help_text='Button text 03 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('about_me', wagtail.core.blocks.StructBlock([('image_table', wagtail.images.blocks.ImageChooserBlock(help_text='Enter the image for the left table', label='Image Table')), ('title_table', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading of the table', label='Left Title Table')), ('table', streams.blocks.AnyTableBlock()), ('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading', label='Right Title RichText')), ('ricktext', wagtail.core.blocks.StructBlock([('context', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h2', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'subscript', 'strikethrough', 'blockquote'], help_text='Enter your richtext here'))])), ('link_cv_document', wagtail.documents.blocks.DocumentChooserBlock()), ('btn_download_text', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter 2 texts for btn', label='First Button Text')), ('hire_url', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='More details', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Write the url to link to', label='Hire Button URL')), ('btn_hire_text', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter 2 texts for btn', label='Second Button Text'))])), ('education', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading')), ('education_block', wagtail.core.blocks.ListBlock(streams.blocks.EducationBlock))])), ('progress_bars', wagtail.core.blocks.StructBlock([('progress_bar', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter percentage and title')))])), ('experience', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading')), ('experience_block', wagtail.core.blocks.ListBlock(streams.blocks.ExperienceBlock))])), ('services', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading')), ('services', wagtail.core.blocks.ListBlock(streams.blocks.ServiceBlock))])), ('my_projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading')), ('data_filter_01', wagtail.core.blocks.CharBlock(help_text='Max length 60 characters', max_length=60, required=False)), ('data_filter_02', wagtail.core.blocks.CharBlock(help_text='Max length 60 characters', max_length=60, required=False)), ('data_filter_03', wagtail.core.blocks.CharBlock(help_text='Max length 60 characters', max_length=60, required=False)), ('data_filter_04', wagtail.core.blocks.CharBlock(help_text='Max length 60 characters', max_length=60, required=False)), ('my_project_block', wagtail.core.blocks.ListBlock(streams.blocks.MyProjectBlock))])), ('testimonial', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading')), ('testimonials', wagtail.core.blocks.ListBlock(streams.blocks.TestimonialBlock))]))], blank=True, null=True),
        ),
    ]
