# Generated by Django 3.1.9 on 2021-05-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0006_auto_20210518_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='button_01',
            field=models.ForeignKey(blank=True, help_text='Select an optional page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_02',
            field=models.URLField(blank=True, help_text='Write the url to link to', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_03',
            field=models.URLField(blank=True, help_text='Write the url to link to', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_01_1',
            field=models.CharField(default='Read More', help_text='Button text 01 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_01_2',
            field=models.CharField(default='Read More', help_text='Button text 01 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_02_1',
            field=models.CharField(default='Read More', help_text='Button text 02 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_02_2',
            field=models.CharField(default='Read More', help_text='Button text 02 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_03_1',
            field=models.CharField(default='Read More', help_text='Button text 03 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_03_2',
            field=models.CharField(default='Read More', help_text='Button text 03 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_text_down_01',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_text_down_02',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_text_down_03',
            field=models.CharField(blank=True, help_text='Subheading text below the heading title 3', max_length=255),
        ),
    ]
