# Generated by Django 3.1.9 on 2021-05-21 18:09

from django.db import migrations, models
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210521_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('about_me', wagtail.core.blocks.StructBlock([('title_table', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading of the table', label='Left Title Table')), ('table', streams.blocks.AnyTableBlock()), ('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading', label='Right Title RichText')), ('ricktext', wagtail.core.blocks.StructBlock([('context', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h2', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'subscript', 'strikethrough', 'blockquote']))], help_text='Enter your richtext here')), ('link_cv_document', wagtail.documents.blocks.DocumentChooserBlock()), ('btn_download_text', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter 2 texts for btn', label='First Button Text')), ('btn_hire_text', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter 2 texts for btn', label='Second Button Text'))])), ('education', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading'))])), ('progress_bars', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading'))])), ('experience', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading'))])), ('services', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading'))])), ('my_projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading'))])), ('testimonial', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.CharBlock(help_text='Enter sub-heading', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Enter heading', required=True))], help_text='Enter heading and subheading')), ('testimonials', wagtail.core.blocks.ListBlock(streams.blocks.TestimonialBlock))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_01_1',
            field=models.CharField(default='Download CV', help_text='Button text 01 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_01_2',
            field=models.CharField(default='Download', help_text='Button text 01 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_02_1',
            field=models.CharField(default='Send Message', help_text='Button text 02 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_02_2',
            field=models.CharField(default='SEND', help_text='Button text 02 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_03_1',
            field=models.CharField(default='Hire Me', help_text='Button text 03 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_text_03_2',
            field=models.CharField(default='HIRE', help_text='Button text 03 2', max_length=50),
        ),
    ]
