# Generated by Django 3.1.9 on 2021-05-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Flex (misc) page',
                'verbose_name_plural': 'Flex (misc) pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
