# Generated by Django 3.1.9 on 2021-05-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('menus', '0003_menuitem_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
